import { API_ENDPOINTS } from "../ApiEndpoints/apiEndpoints";

export const QUERY_KEYS = {
  INIT: [API_ENDPOINTS.INIT],
  USERS: [API_ENDPOINTS.STAFF_MANAGEMENT.GET_USERS],
  ACTIVE_ROLES: [API_ENDPOINTS.ROLES_MANAGEMENT.ACTIVE_ROLES],
  GET_ROLES: [API_ENDPOINTS.ROLES_MANAGEMENT.GET_ROLES],
  GET_ATTENDANCE: [API_ENDPOINTS.ATTENDANCE_MANAGEMENT.GET],
  GET_ALL_BRANCH: [API_ENDPOINTS.BRANCH.GET],
  GET_SUBSCRIPTION: [API_ENDPOINTS.SUBSCRIPTION.GET],
  GET_CLIENT: [API_ENDPOINTS.CLIENT_MANAGEMENT.GET],
  GET_FOLLOWUP: (days: number, branch: number | undefined) =>
    API_ENDPOINTS.FOLLOWUP.GET(days, branch),
  GET_CATEGORY: [API_ENDPOINTS.PRODUCT_MANAGEMENT.CATEGORY],
  GET_SALES: [API_ENDPOINTS.SALES_MANAGEMENT.GET],
  GET_PRODUCT: (id: number) => API_ENDPOINTS.PRODUCT_MANAGEMENT.GET_PRODUCT(id),
  GET_CLIENT_HISTORY: (id: any) => [API_ENDPOINTS.CLIENT_HISTORY.GET(id)],
  GET_ALL_PRODUCT: [API_ENDPOINTS.PRODUCT_MANAGEMENT.GET_ALL_PRODUCT],
  GET_TOP_USED_PRODUCT: (timeFrame: string) => [
    API_ENDPOINTS.DASHBOARD.GET_TOP_PRODUCT(timeFrame),
  ],
  GET_TOP_USED_TREATMENT: (timeFrame: string) => [
    API_ENDPOINTS.DASHBOARD.GET_TOP_TREATMENT(timeFrame),
  ],
  GET_DASHBOARD_DETAILS: [API_ENDPOINTS.DASHBOARD.GET_DASHBOARD_DETAILS],
  GET_DASHBOARD_ALL_APPOINTMENTS: [
    API_ENDPOINTS.DASHBOARD.GET_ALL_APPOINTMENTS,
  ],
};
